Fix error in deseq2
This error occurs when running deseq2
```
deseq2: Error: package or namespace load failed for 'GenomeInfoDb' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
there is no package called 'GenomeInfoDbData'
Error: package 'GenomeInfoDb' could not be loaded
```
Version 2.11.40.2

Version 2.11.39 does not have the issue