Add missing openSSL
Should fix:
```
Warning message:
In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
  OS reports request to set locale to "en_US.UTF-8" cannot be honored
Error: package or namespace load failed for ‘geneLenDataBase’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/rtracklayer/libs/rtracklayer.so':
  libssl.so.1.1: cannot open shared object file: No such file or directory
Error: package ‘geneLenDataBase’ could not be loaded
Warning message:
replacing previous import ‘utils::download.file’ by ‘restfulr::download.file’ when loading ‘rtracklayer’
Warning message:
In Sys.setlocale("LC_MESSAGES", "en_US.UTF-8") :
  OS reports request to set locale to "en_US.UTF-8" cannot be honored
Error: package or namespace load failed for ‘geneLenDataBase’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/library/rtracklayer/libs/rtracklayer.so':
  libssl.so.1.1: cannot open shared object file: No such file or directory
Error: package ‘geneLenDataBase’ could not be loaded
Warning message:
replacing previous import ‘utils::download.file’ by ‘restfulr::download.file’ when loading ‘rtracklayer’

```