Fix crossmap_bam tests
No need to use lines_diff (there are no randomly changed lines in
the SAM version of the BAMs).

But we need to specify `ftype="bam"` for the output data, otherwise
Galaxy won't convert them to SAM when checking the outputs and fail
with:

```
======================================================================
FAIL: CrossMap BAM ( crossmap_bam ) > Test-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/galaxy/test/functional/test_toolbox.py", line 316, in test_tool
    self.do_it(td)
  File "/opt/galaxy/test/functional/test_toolbox.py", line 82, in do_it
    raise e
JobOutputsError: History item  different than expected, difference (using diff):
( /usr/users/ga002/soranzon/software/nsoranzo_tools-iuc/tools/crossmap/test-data/test_bam_01_output_a.bam v. /tmp/tmppCnzEytest_bam_01_output_a.bam )
Binary data detected, not displaying diff

======================================================================
FAIL: CrossMap BAM ( crossmap_bam ) > Test-2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/galaxy/test/functional/test_toolbox.py", line 316, in test_tool
    self.do_it(td)
  File "/opt/galaxy/test/functional/test_toolbox.py", line 82, in do_it
    raise e
JobOutputsError: History item  different than expected, difference (using diff):
( /usr/users/ga002/soranzon/software/nsoranzo_tools-iuc/tools/crossmap/test-data/test_bam_01_output_a.bam v. /tmp/tmp457bzptest_bam_01_output_a.bam )
Binary data detected, not displaying diff
```