GMAP test case
Still need to tweak the command and/or paramters somehow,
otherwise fails to build the command string with:

Exception: invalid literal for int() with base 10: ''

(Can get this to pass by removing most of the command string
definition!)