Modernize busco tool and datamanager (#6808)
* busco DM: consider odb version

recently odb12 became available for prokaryotes.
download would now mix now odb10 and 12.
see https://gitlab.com/ezlab/busco/-/issues/784

we unfortunately have no version column .. but having
it in the name and label might be OK

* fix variable name

* fix BUSCO DM

* add datamanager for determining the possible lineage choices

* - make tool offline only (admins should download the DB)
- update augustus species
- use dynamically created lineage choices

* use find to remove unneeded data

* BUSCO DM: unpack all faa

* stash

* busco DM: use version

* BUSCO: finalize

- use mock DB copy for IUC tests
- document local testing for real life scenario (using `--offline`)

* add missing loc.sample file

* add fna and faa outputs

https://help.galaxyproject.org/t/forming-orthogroups-using-busco-and-access-to-busco-sequences-output/12709

* ibeautify augistus species list

* add help on augustus parameters

* allow gz input

* pin augustus

* busco_options DM: reset suffix version

Co-authored-by: Björn Grüning <bjoern@gruenings.eu>

* add quotes

Co-authored-by: Björn Grüning <bjoern@gruenings.eu>

* Remove debug `ls`

Co-authored-by: Björn Grüning <bjoern@gruenings.eu>

* Uncomment test

* Improve validator message

* Fixup uncomment test

* force conda to use compatible sepp and denropy

otherwise sepp fails with

```
Traceback (most recent call last):
  File "/usr/local/bin/run_sepp.py", line 3, in <module>
    from sepp.exhaustive import ExhaustiveAlgorithm
  File "/usr/local/lib/python3.9/site-packages/sepp/exhaustive.py", line 6, in <module>
    from sepp.algorithm import AbstractAlgorithm
  File "/usr/local/lib/python3.9/site-packages/sepp/algorithm.py", line 12, in <module>
    from sepp.tree import PhylogeneticTree
  File "/usr/local/lib/python3.9/site-packages/sepp/tree.py", line 25, in <module>
    from dendropy.datamodel.treemodel import _convert_node_to_root_polytomy as \
ImportError: cannot import name '_convert_node_to_root_polytomy' from 'dendropy.datamodel.treemodel' (/usr/local/lib/python3.9/site-packages/dendropy/datamodel/treemodel/__init__.py)
```

---------

Co-authored-by: Björn Grüning <bjoern@gruenings.eu>