Irissv: fix errors related to bai file creation (#4642)
* switch to aggressive error detection

otherwise the following is missed

```
java.lang.Exception: running samtools index on /tmp/tmpeadmabrl/files/9/f/5/dataset_9f501fd8-0c14-4cd4-a208-f69b432f5170.dat failed: samtools index /tmp/tmpeadmabrl/files/9/f/5/dataset_9f501fd8-0c14-4cd4-a208-f69b432f5170.dat
	at ReadGathering.extractReads(ReadGathering.java:82)
	at ReadGathering.getReads(ReadGathering.java:26)
	at NewSequenceMap.fromReadNames(NewSequenceMap.java:46)
	at ParallelRunningStitch$Rayon.run(ParallelRunningStitch.java:84)
	at ParallelRunningStitch.run(ParallelRunningStitch.java:48)
	at Iris.runIris(Iris.java:15)
	at Iris.main(Iris.java:4)
```

* link bai file