GMAP split_output workaround
Direct boolean testing should work (thanks Nicola), while
the first usage does not need an if statement as the value
is empty when false.

Avoids https://github.com/galaxyproject/galaxy/issues/998
ValueError: invalid literal for int() with base 10: ''