fgbio findswitchbackreads (#7383)
* git commit -m initial wrappers

* Enable tool to load with `planemo serve`

Stop the tool from failing in `planemo serve` and `planemo test` with
error:
ValueError: invalid literal for int() with base 10: 'dbkey'

* Add test 1 with fixtures

Currently fails because the bam tool output is queryname sorted, not
coordinate sorted.

* Always sort output bam by coordinate

Remove sort_order (Output sort order) parameter, to prevent the tool
from failing with this error message in the log file:

pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=,
stderr=samtools index: failed to create index for ...: Inappropriate
ioctl for device\n'

* Add test 2 initial version

Must fail.

* Fix to pass 0 values to numeric params

And make test 2 initial version fail as expected.

* Fix test 2

As expected, test 2 passes when used with the expected output bam
file.

* Specify memory as recommended

* removes partial tool wrappers

* moves from tool_collections to tools, seems more typical of current use

* addresses linting issues

* adds missing samtools dependency

* switches from a tool to a suite on mattias' recommendation

* switches to use of truevalue for simpler command construction

* shorter description

* adds argument attributes

* Update tool_collections/fgbio/.shed.yml

Co-authored-by: Saim Momin <64724322+SaimMomin12@users.noreply.github.com>

* use GALAXY_MEMORY variable for easier configuration

* requested shed.yml updates

* admins can set _JAVA_OPTIONS in job_conf to allow more memory usage

* bash variable -> cheetah

* reverts accidental samtools change

* macros.xml fix, aparently relative paths are not allowd for macros

* reverts trailing space removal

* back to bash reffa ... cheetah version did not work

* switches to flat structure

* corrects citation - not sure where that doi came from...

---------

Co-authored-by: Timur Shtatland <shtatland@neb.com>
Co-authored-by: Saim Momin <64724322+SaimMomin12@users.noreply.github.com>