Fix hisat2 interleaved unmapped output
Also produce the (R) aligned/unaligned read outputs for interleaved input,
so both mates are moved into the right datasets instead of the (L) output
staying empty.

Fixes:
```
Exception caught while attempting to execute tool with id 'toolshed.g2.bx.psu.edu/repos/iuc/hisat2/hisat2/2.2.1+galaxy1':

AttributeError: 'HistoryDatasetAssociation' object has no attribute 'forward'
  File "galaxy/tools/__init__.py", line 1968, in handle_single_execution
    rval = self.execute(
  File "galaxy/tools/__init__.py", line 2065, in execute
    return self.tool_action.execute(
  File "galaxy/tools/actions/__init__.py", line 652, in execute
    handle_output(name, output)
  File "galaxy/tools/actions/__init__.py", line 573, in handle_output
    output.actions.apply_action(data, output_action_params)
  File "galaxy/tool_util/parser/output_actions.py", line 40, in apply_action
    action.apply_action(output_dataset, other_values)
  File "galaxy/tool_util/parser/output_actions.py", line 118, in apply_action
    case.apply_action(output_dataset, other_values)
  File "galaxy/tool_util/parser/output_actions.py", line 81, in apply_action
    super().apply_action(output_dataset, other_values)
  File "galaxy/tool_util/parser/output_actions.py", line 40, in apply_action
    action.apply_action(output_dataset, other_values)
  File "galaxy/tool_util/parser/output_actions.py", line 341, in apply_action
    value = self.option.get_value(other_values)
  File "galaxy/tool_util/parser/output_actions.py", line 255, in get_value
    value = getattr(value, attr_name)
  File "galaxy/tools/wrappers.py", line 494, in __getattr__
    return getattr(self.dataset, key)
  File "galaxy/security/object_wrapper.py", line 322, in __getattr__
    return self.__safe_string_wrapper_function__(getattr(self.unsanitized, name))
```

from https://sentry.galaxyproject.org/share/issue/0fa92ec28aec436b9923ab47c1a73c06/