Fix broken data_manager_humann2_database_downloader
$ planemo shed_lint --tools --ensure_metadata --urls --report_level warn --fail_level error data_managers/data_manager_humann2_database_downloader/
Linting repository /usr/users/ga002/soranzon/software/galaxyproject_tools-iuc/data_managers/data_manager_humann2_database_downloader
Error loading tool with path /tmp/planemo_tmp_yfUlf1/83901c99b429ead8a454823bbaa1c331/data_manager_humann2_database_downloader/data_manager/data_manager_humann2_download.xml
Traceback (most recent call last):
  File "/usr/users/ga002/soranzon/software/galaxyproject_planemo/.venv/local/lib/python2.7/site-packages/galaxy/tools/loader_directory.py", line 107, in _load_tools_from_path
    tool_element = loader_func(possible_tool_file)
ParseError: not well-formed (invalid token): line 49, column 32
+Linting tool /usr/users/ga002/soranzon/software/galaxyproject_tools-iuc/data_managers/data_manager_humann2_database_downloader/data_manager/data_manager_humann2_download.xml
Could not lint /tmp/planemo_tmp_yfUlf1/83901c99b429ead8a454823bbaa1c331/data_manager_humann2_database_downloader/data_manager/data_manager_humann2_download.xml due to malformed xml.
Failed linting

Also drop deprecated interpreter attribute of <command>.